ergo-web2-2023/Areas/Administrator/Controllers/SubquestionController.cs
using AutoMapper;
using ergo_web2_2023.Areas.Administrator.ViewModels;
using ergo_web2_2023.Models.Entities;
using ergo_web2_2023.Repositories.Interfaces;
using ergo_web2_2023.Services;
using ergo_web2_2023.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using System.Data;

namespace ergo_web2_2023.Areas.Administrator.Controllers
{
    [Authorize]
    [Area("Administrator")]
    public class SubquestionController : Controller
    {

        private IBasicOperationService<Subquestion> _subquestionService;
        private IBasicOperationService<Question> _questionService;
        private IQuestionOptionService<QuestionOption> _optionService;
        private readonly IMapper _mapper;

        public SubquestionController(
            IMapper mapper,
            IBasicOperationService<Subquestion> subquestionService,
            IBasicOperationService<Question> questionService,
            IQuestionOptionService<QuestionOption> optionService)
        {
            _mapper = mapper;
            _subquestionService = subquestionService;
            _questionService = questionService;
            _optionService = optionService;
        }

        public IActionResult Index()
        {
            return RedirectToAction("ListAllSubquestions");
        }

        public async Task<int> GetNextSubquestionId()
        {
            var subquestions = await _subquestionService.GetAll();
            return subquestions.Count() + 1;
        }

        public async Task<IActionResult> ListAllSubquestions()
        {
            var list = await _subquestionService.GetAll();
            List<SubquestionVM> listVM = _mapper.Map<List<SubquestionVM>>(list);
            return View(listVM);
        }

        [HttpGet]
        public async Task<IActionResult> GetOptions(int questionId)
        {
            var options = await _optionService.GetOptionsOfQuestion(questionId);
            return Json(options);
        }

        public async Task<IActionResult> CreateSubquestion()
        {
            var subquestionVM = new SubquestionAddVM()
            {
                Vragen = new SelectList(await _questionService.GetAll(), "QuestionId", "Title"),
                Subvragen = new SelectList(await _questionService.GetAll(), "QuestionId", "Title"),
                Options = new SelectList(new List<SelectListItem>())
            };
            return View(subquestionVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSubquestion(SubquestionAddVM entityVM)
        {
            if(entityVM.SubQuestionId == entityVM.QuestionId)
            {
                ModelState.AddModelError("Vragen", "Question en subquestion mogen niet dezelfde waarde hebben.");
            }

            try
            {
                if (ModelState.IsValid)
                {
                    var subquestion = _mapper.Map<Subquestion>(entityVM);
                    // subquestion.SubQuestionId = await GetNextSubquestionId();
                    await _subquestionService.Add(subquestion);
                    return RedirectToAction("ListAllSubquestions");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return await CreateSubquestion();
        }

        public async Task<IActionResult> EditSubquestion(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                Subquestion? subquestion = await _subquestionService.FindById(Convert.ToInt16(id));
                var subquestionEdit = _mapper.Map<SubquestionEditVM>(subquestion);
                subquestionEdit.Vragen = new SelectList(await _questionService.GetAll(), "QuestionId", "Title", subquestion.QuestionId);
                subquestionEdit.Subvragen = new SelectList(await _questionService.GetAll(), "QuestionId", "Title", subquestion.SubQuestionId);
                subquestionEdit.Options = new SelectList(new List<SelectListItem>());

                return View(subquestionEdit);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSubquestion(SubquestionEditVM entityVM)
        {
            if (entityVM.SubQuestionId == entityVM.QuestionId)
            {
                ModelState.AddModelError("Vragen", "Question en subquestion mogen niet dezelfde waarde hebben.");
            }
            try
            {
                if (ModelState.IsValid)
                {
                    var subquestion = _mapper.Map<Subquestion>(entityVM);
                    await _subquestionService.Update(subquestion);
                    return RedirectToAction("ListAllSubquestions");
                }
            }
            catch (DataException ex)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            catch (Exception ex)
            {
                ModelState.AddModelError(ex.Message, "call system administrator.");
                System.Diagnostics.Debug.WriteLine(ex.Message);
            }
            return await EditSubquestion(entityVM.Id);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return Index();
            }
            else
            {
                Subquestion ? subquestion = await _subquestionService.FindById(Convert.ToInt16(id));

                var subquestionVM = _mapper.Map<SubquestionVM>(subquestion);

                return View(subquestionVM);
            }
        }

        public async Task<IActionResult> DeleteSubquestion(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                Subquestion subquestion = await _subquestionService.FindById(Convert.ToInt32(id));
                if (subquestion == null)
                {
                    return NotFound();
                }
                await _subquestionService.Delete(subquestion);
                return RedirectToAction("ListAllSubquestions");
            }
            catch (DataException ex)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to delete data.");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Call the administrator");
            }
            return RedirectToAction("ListAllSubquestions");
        }
    }
}

ergo-web2-2023/Areas/Administrator/Views/Subquestion/CreateSubquestion.cshtml
@model ergo_web2_2023.Areas.Administrator.ViewModels.SubquestionAddVM
<link rel="stylesheet" href="~/css/editAndCreate.css">

@{
    ViewData["Title"] = "CreateSubquestion";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}
<div class="container align-content-center">

    <h1>New Subquestion</h1>

    <br />
    <div class="scrollable-container">
        <div class="row">
            <div class="col-4"></div>

            <div class="col-md-4">
                <form asp-action="CreateSubquestion" id="editSubquestionForm">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="SubQuestionId" class="control-label"></label>

                        <select asp-for="SubQuestionId" class="form-control"
                                asp-items="@Model.Subvragen">
                            <option>Please select</option>
                        </select>
                        <span asp-validation-for="SubQuestionId" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="QuestionId" class="control-label"></label>

                        <select asp-for="QuestionId" id="questionDropdown" class="form-control"
                                asp-items="@Model.Vragen">
                            <option>Please select</option>
                        </select>
                        <span asp-validation-for="QuestionId" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="OptionId" class="control-label"></label>

                        <select asp-for="OptionId" id="optionsDropdown" class="form-control"
                                asp-items="@Model.Options">
                            <option>Please select</option>
                        </select>
                        <span asp-validation-for="OptionId" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                        <p class="text-danger">@Html.ValidationMessage("Vragen")</p>
                    </div>
                </form>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            function loadOptions() {
                var selectedQuestionId = $('#questionDropdown').val();
                var optionsDropdown = $('#optionsDropdown');

                if (selectedQuestionId !== '') {
                    optionsDropdown.prop('disabled', false);

                    $.ajax({
                        url: '@Url.Action("GetOptions", "Subquestion")',
                        type: 'GET',
                        data: { questionId: selectedQuestionId },
                        success: function (data) {
                            optionsDropdown.empty();

                            if (data.length === 0) {
                                optionsDropdown.append($('<option></option>').val(0).text('Geen Opties'));
                            }

                            $.each(data, function (index, option) {
                                optionsDropdown.append($('<option></option>').val(option.optionId).text(option.optiontext));
                            });
                        },
                        error: function () {
                            console.log('Failed to retrieve options for the selected question.');
                        }
                    });
                } else {
                    optionsDropdown.empty().prop('disabled', true);
                }
            }

            $('#questionDropdown').on('change', function () {
                loadOptions();
            });

            loadOptions();
        });
    </script>
}

ergo-web2-2023/Areas/Administrator/Views/Subquestion/Delete.cshtml
@model ergo_web2_2023.Areas.Administrator.ViewModels.SubquestionVM
<link rel="stylesheet" href="~/css/editAndCreate.css">

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div class="container align-content-center">
    <h1>Delete this subquestion?</h1>
    <br />
    <div class="scrollable-container">
        <div class="row">
            <div class="col-4"></div>

            <div class="col-md-4">
                     @using (Html.BeginForm("DeleteSubquestion", "Subquestion", new { id = Model.Id }, FormMethod.Post))
                {
                    <div>
                        <label class="control-label">Subquestion Title</label>
                        <input value="@Model.SubQuestionTitle" class="form-control" readonly />
                    </div>
                    <div>
                        <label class="control-label">Question Title</label>
                        <input value="@Model.QuestionTitle" class="form-control" readonly />
                    </div>
                    <div>
                        <label class="control-label">Option Id</label>
                        <input value="@Model.OptionId" class="form-control" readonly />
                    </div>

                    @Html.AntiForgeryToken()
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-danger delete">Delete</button>
                            </div>
                            <div class="col-6">
                                <button type="button" class="btn cancel" onclick="location.href='@Url.Action("ListAllSubquestions")'">Cancel</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</div>

ergo-web2-2023/Areas/Administrator/Views/Subquestion/EditSubquestion.cshtml
@model ergo_web2_2023.Areas.Administrator.ViewModels.SubquestionEditVM
<link rel="stylesheet" href="~/css/editAndCreate.css">
@{
    ViewData["Title"] = "EditSubquestion";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div class="container align-content-center">

    <h1>Edit Subquestion</h1>

    <br />
    <div class="scrollable-container">
        <div class="row">
            <div class="col-4"></div>

            <div class="col-md-4">
                <form asp-action="EditSubquestion" id="createSubquestionForm">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="Id" class="control-label" hidden></label>
                        <input asp-for="Id" class="form-control" hidden />
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SubQuestionId" class="control-label"></label>
                        <input asp-for="SubQuestionId" class="form-control" hidden />
                        <select asp-for="SubQuestionId" class="form-control" disabled
                                asp-items="@Model.Subvragen">
                        </select>
                        <span asp-validation-for="SubQuestionId" class="text-danger"></span>
                    </div>
                    <br />

                    <div class="form-group">
                        <label asp-for="QuestionId" class="control-label"></label>
                        <select asp-for="QuestionId" id="questionDropdown" class="form-control"
                                asp-items="@Model.Vragen">
                        </select>
                        <span asp-validation-for="QuestionId" class="text-danger"></span>
                    </div>
                    <br />

                    <div class="form-group">
                        <label asp-for="OptionId" class="control-label"></label>

                        <select asp-for="OptionId" id="optionsDropdown" class="form-control"
                                asp-items="@Model.Options">
                            <option>Please select</option>
                        </select>
                        <span asp-validation-for="OptionId" class="text-danger"></span>
                    </div>

                    <br />

                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                        <p class="text-danger">@Html.ValidationMessage("Vragen")</p>
                    </div>
                </form>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            function loadOptions() {
                var selectedQuestionId = $('#questionDropdown').val();
                var optionsDropdown = $('#optionsDropdown');

                if (selectedQuestionId !== '') {
                    optionsDropdown.prop('disabled', false);

                    $.ajax({
                        url: '@Url.Action("GetOptions", "Subquestion")',
                        type: 'GET',
                        data: { questionId: selectedQuestionId },
                        success: function (data) {
                            optionsDropdown.empty();

                            if (data.length === 0) {
                                optionsDropdown.append($('<option></option>').val(0).text('Geen Opties'));
                            }

                            $.each(data, function (index, option) {
                                optionsDropdown.append($('<option></option>').val(option.optionId).text(option.optiontext));
                            });
                        },
                        error: function () {
                            console.log('Failed to retrieve options for the selected question.');
                        }
                    });
                } else {
                    optionsDropdown.empty().prop('disabled', true);
                }
            }

            $('#questionDropdown').on('change', function () {
                loadOptions();
            });

            loadOptions();
        });
    </script>
}

ergo-web2-2023/Areas/Administrator/Views/Subquestion/ListAllSubquestions.cshtml
@model IEnumerable<ergo_web2_2023.Areas.Administrator.ViewModels.SubquestionVM>

@{
    ViewData["Title"] = "ListAllSubquestions";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div id="quick-actions">
    <h3>Quick Actions</h3>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-3 mb-2" onclick="location.href='@Url.Action("CreateSubquestion", "Subquestion", new { area = "Administrator" })';" style="cursor: pointer;">
            <div class="card text-center">
                <div class="card-body fw-bold">
                    <p>
                        <h3 class="plus">+</h3>
                        <span>Create Subquestion</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="content">
    <div class="content-title">
        <h3>All Subquestions</h3>
    </div>
    <div class="row content-cards">
        @foreach (var item in Model)
        {
            <div class="col-12 col-md-6 col-lg-3 mb-2">
                <div class="card content-card">
                    <div class="card-body">
                        <h5 class="formtitle">@Html.DisplayFor(modelItem => item.SubQuestionTitle)</h5>
                        <p class="description">Question title: @Html.DisplayFor(modelItem => item.QuestionTitle)</p>
                    </div>
                    <div class="actions">
                        <a asp-action="EditSubquestion" asp-route-id="@item.Id"><img height="30px" src="~/images/edit.png" /></a> |
                        <a asp-action="Delete" asp-route-id="@item.Id"><img height="30px" src="~/images/delete.png" /></a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>