ergo-web2-2023/Areas/Administrator/Controllers/FormGroupController.cs
using AutoMapper;
using ergo_web2_2023.Areas.Administrator.ViewModels;
using ergo_web2_2023.Models.Entities;
using ergo_web2_2023.Repositories.Interfaces;
using ergo_web2_2023.Services;
using ergo_web2_2023.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace ergo_web2_2023.Areas.Administrator.Controllers
{
    [Authorize]
    [Area("Administrator")]
    public class FormGroupController : Controller
    {

        private IBasicOperationService<FormGroup> _formGroupService;
        private IFormQuestionService<FormQuestion> _formQuestionService;
        private IBasicOperationService<FormQuestion> _formQuestionBasicService;
        private readonly IMapper _mapper;

        public FormGroupController(
            IMapper mapper,
            IBasicOperationService<FormGroup> formGroupService,
            IFormQuestionService<FormQuestion> formQuestionService,
            IBasicOperationService<FormQuestion> formQuestionBasicService)
        {
            _mapper = mapper;
            _formGroupService = formGroupService;
            _formQuestionService = formQuestionService;
            _formQuestionBasicService = formQuestionBasicService;
        }
        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> CreateFormGroup()
        {
            FormGroupVM formGroupVM = new FormGroupVM();
            return View(formGroupVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateFormGroup(FormGroupVM entityVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var formGroup = _mapper.Map<FormGroup>(entityVm);
                    await _formGroupService.Add(formGroup);
                    return RedirectToAction("ListAllGroups");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return RedirectToAction("ListAllGroups");
        }

        public async Task<IActionResult> ListAllGroups()
        {
            var list = await _formGroupService.GetAll();
            List<FormGroupVM> listVM = _mapper.Map<List<FormGroupVM>>(list);
            return View(listVM);
        }

        public async Task<IActionResult> EditGroup(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                FormGroup? group = await _formGroupService.FindById(Convert.ToInt16(id));
                var formGroup = _mapper.Map<FormGroupVM>(group);
                return View(formGroup);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditGroup(FormGroupVM entityVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var group = _mapper.Map<FormGroup>(entityVM);
                    await _formGroupService.Update(group);
                    return RedirectToAction("ListAllGroups");
                }
            }
            catch (DataException ex)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            catch (Exception ex)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError(ex.Message, "call system administrator.");
                System.Diagnostics.Debug.WriteLine(ex.Message);
            }
            return View(entityVM);
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return Index();
            }
            else
            {
                FormGroup? formGroup = await _formGroupService.FindById(Convert.ToInt16(id));
                var formGroupVM = _mapper.Map<FormGroupVM>(formGroup);

                return View(formGroupVM);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                FormGroup formGroup = await _formGroupService.FindById(Convert.ToInt32(id));
                var formQuestions = await _formQuestionService.GetFormQuestionsOfGroup(Convert.ToInt32(id));
                if (formQuestions != null)
                {
                    foreach (FormQuestion formQuestion in formQuestions)
                    {
                        await _formQuestionBasicService.Delete(formQuestion);
                    }
                }
                if (formGroup == null)
                {
                    return NotFound();
                }
                await _formGroupService.Delete(formGroup);
                return RedirectToAction("ListAllGroups");
            }
            catch (DataException)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to delete data.");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Call the administrator");
            }
            return RedirectToAction("ListAllGroups");
        }
    }
}

ergo-web2-2023/Areas/Administrator/Views/FormGroup/CreateFormGroup.cshtml
@model ergo_web2_2023.Areas.Administrator.ViewModels.FormGroupVM
<link rel="stylesheet" href="~/css/editAndCreate.css">

@{
    ViewData["Title"] = "CreateFormGroup";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div class="container align-content-center">
    <h1>New Form Group</h1>
    <br />
    <div class="scrollable-container">
        <div class="row">
            <div class="col-4"></div>

            <div class="col-md-4">
                <form asp-action="CreateFormGroup">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="GroupOrder" class="control-label"></label>
                        <input asp-for="GroupOrder" class="form-control" id="GroupOrder"/>
                        <span asp-validation-for="GroupOrder" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        var numberInput = document.getElementById("GroupOrder");

        numberInput.addEventListener("input", function () {
            if (numberInput.value < 1) {
                numberInput.value = 1;
            }
        });
       
    </script>
}

ergo-web2-2023/Areas/Administrator/Views/FormGroup/Delete.cshtml
@model ergo_web2_2023.Areas.Administrator.ViewModels.FormGroupVM
<link rel="stylesheet" href="~/css/editAndCreate.css">

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div class="container align-content-center">
    <h1>Delete this formgroup?</h1>
    <br />
    <div class="scrollable-container">
        <div class="row">
            <div class="col-4"></div>

            <div class="col-md-4">
                @using (Html.BeginForm("Delete", "FormGroup", new { id = Model.GroupId }, FormMethod.Post))
                {
                    <div>
                        <label class="control-label">Title</label>
                        <input value="@Model.Title" class="form-control" readonly />
                    </div>
                    <div>
                        <label class="control-label">Group Order</label>
                        <input value="@Model.GroupOrder" class="form-control" readonly />
                    </div>

                    @Html.AntiForgeryToken()
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-danger delete">Delete</button>
                            </div>
                            <div class="col-6">
                                <button type="button" class="btn cancel" onclick="location.href='@Url.Action("ListAllGroups")'">Cancel</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</div>

ergo-web2-2023/Areas/Administrator/Views/FormGroup/EditGroup.cshtml
@model ergo_web2_2023.Areas.Administrator.ViewModels.FormGroupVM
<link rel="stylesheet" href="~/css/editAndCreate.css">

@{
    ViewData["Title"] = "EditGroup";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div class="container align-content-center">

    <h1>EditGroup</h1>
    <br />
    <div class="scrollable-container">
        <div class="row">
            <div class="col-4"></div>

            <div class="col-md-4">
                <form asp-action="EditGroup">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="GroupId" class="control-label"></label>
                        <input asp-for="GroupId" class="form-control" />
                        <span asp-validation-for="GroupId" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="GroupOrder" class="control-label"></label>
                        <input asp-for="GroupOrder" class="form-control" />
                        <span asp-validation-for="GroupOrder" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ergo-web2-2023/Areas/Administrator/Views/FormGroup/ListAllGroups.cshtml
@model IEnumerable<ergo_web2_2023.Areas.Administrator.ViewModels.FormGroupVM>

@{
    ViewData["Title"] = "ListAllGroups";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div id="quick-actions">
    <h3>Quick Actions</h3>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-3 mb-2" onclick="location.href='@Url.Action("CreateFormGroup", "FormGroup", new { area = "Administrator" })';" style="cursor: pointer;">
            <div class="card text-center">
                <div class="card-body fw-bold">
                    <p>
                        <h3 class="plus">+</h3>
                        <span>Create Form Group</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="content">
    <div class="content-title">
        <h3>All Form Groups</h3>
    </div>
    <div class="row content-cards">
        @foreach (var item in Model)
        {
            <div class="col-12 col-md-6 col-lg-3 mb-2">
                <div class="card content-card">
                    <div class="card-body">
                        <h5 class="grouptitle">@Html.DisplayFor(modelItem => item.Title)</h5>
                        <p class="groupOrder"></p>
                           <p class="description">Order: @Html.DisplayFor(modelItem => item.GroupOrder)</p>
                    </div>
                    <div class="actions">
                        <a asp-action="EditGroup" asp-route-id="@item.GroupId"><img height="30px" src="~/images/edit.png" /></a> |
                        <a asp-action="Delete" asp-route-id="@item.GroupId"><img height="30px" src="~/images/delete.png" /></a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>