ergo-web2-2023/Areas/Administrator/Controllers/QuestionController.cs
using AutoMapper;
using ergo_web2_2023.Areas.Administrator.ViewModels;
using ergo_web2_2023.Models.Entities;
using ergo_web2_2023.Models.Enums;
using ergo_web2_2023.Repositories.Interfaces;
using ergo_web2_2023.Services;
using ergo_web2_2023.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;

namespace ergo_web2_2023.Areas.Administrator.Controllers
{
    [Authorize]
    [Area("Administrator")]
    public class QuestionController : Controller
    {

        private IBasicOperationService<Question> _questionService;
        private IQuestionOptionService<QuestionOption> _questionOptionService;
        private readonly IMapper _mapper;

        public QuestionController(IMapper mapper, IBasicOperationService<Question> questionService, IQuestionOptionService<QuestionOption> questionOptionService)
        {
            _mapper = mapper;
            _questionService = questionService;
            _questionOptionService = questionOptionService;

        }

        public IActionResult Index()
        {
            return RedirectToAction("ListAllQuestions");
        }

        public async Task<int> GetNextQuestionId()
        {
            var questions = await _questionService.GetAll();
            return questions.Count() + 1;
        }

        public async Task<IActionResult> ListAllQuestions()
        {
            var list = await _questionService.GetAll();
            List<QuestionVM> listVM = _mapper.Map<List<QuestionVM>>(list);
            return View(listVM);
        }

        public async Task<IActionResult> CreateQuestion()
        {
            QuestionVM questionVM = new QuestionVM();
            return View(questionVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateQuestion(QuestionVM entityVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var question = _mapper.Map<Question>(entityVM);
                    //question.QuestionId = await GetNextQuestionId();
                    await _questionService.Add(question);
                    return RedirectToAction("ListAllQuestions");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(entityVM);
        }

        public async Task<IActionResult> EditQuestion(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                Question? question = await _questionService.FindById(Convert.ToInt16(id));
                var questionEdit = _mapper.Map<QuestionEditVM>(question);
                return View(questionEdit);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditQuestion(QuestionEditVM entityVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var question = _mapper.Map<Question>(entityVM);
                    await _questionService.Update(question);
                    return RedirectToAction("ListAllQuestions");
                }
            }
            catch (DataException ex)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            catch (Exception ex)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError(ex.Message, "call system administrator.");
                System.Diagnostics.Debug.WriteLine(ex.Message);
            }
            return View(entityVM);
        }

        public async Task<IActionResult> AddOptions(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                Question? question = await _questionService.FindById(Convert.ToInt16(id));
                OptionsVM options = new OptionsVM();
                options.Title = question.Title;
                options.Options = question.QuestionOptions;
                options.QuestionId = id;
                return View(options);
            }
        }

        public async Task<IActionResult> InsertNewOption(int questionId, string optionText)
        {
            try
            {
                QuestionOption option = new QuestionOption();
                option.Optiontext = optionText;
                option.QuestionId = questionId;
                IEnumerable<QuestionOption> options = await _questionOptionService.GetOptionsOfQuestion(questionId);
                option.Question = await _questionService.FindById(questionId);
                _questionOptionService.CreateOption(option);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return RedirectToAction("AddOptions", new { id = questionId });
        }

        public async Task<IActionResult> DeleteOption(int optionId, int questionId)
        {
            try
            {
                QuestionOption option = await _questionOptionService.FindById(optionId);
                _questionOptionService.Delete(option);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return RedirectToAction("AddOptions", new { id = questionId });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return Index();
            }
            else
            {

                Question? question = await _questionService.FindById(Convert.ToInt16(id));
                var questionVM = _mapper.Map<QuestionVM>(question);

                return View(questionVM);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                Question question = await _questionService.FindById(Convert.ToInt32(id));
                if (question == null)
                {
                    return NotFound();
                }
                await _questionService.Delete(question);
            }
            catch (DataException ex)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to delete data.");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to delete this question as it's being used in a form.");
            }
            return RedirectToAction("ListAllQuestions");
        }
    }
}

ergo-web2-2023/Areas/Administrator/Views/Question/AddOptions.cshtml
@using ergo_web2_2023.Areas.Administrator.ViewModels
@model ergo_web2_2023.Areas.Administrator.ViewModels.OptionsVM
<link rel="stylesheet" href="~/css/editAndCreate.css">

@{
    ViewData["Title"] = "EditQuestion";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div class="container align-content-center">
    <h1>Add Options</h1>

    <br />
    <div class="row container-row">
        <div class="col-4"></div>
        <div class="col-md-4">

            <input type="text" id="newOptionText" />
            <button class="btn btn-primary mb-5" onclick="insertNewOption()">Insert New Option</button>
            <div class="scrollable-container">

                @foreach (var item in Model.Options)
                {
                    <div class="option">
                        <div class="listItem option-text">
                            @Html.DisplayFor(modelItem => item.Optiontext)
                        </div>
                        <div class="option-delete">
                            <a href="@Url.Action("DeleteOption", new { optionId = item.OptionId, questionId = item.QuestionId })">
                                <img height="30px" src="~/images/delete.png" />
                            </a>
                        </div>
                    </div>
                }
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</div>

@section Scripts
    {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<script>
    function insertNewOption() {
        const questionId = @Model.QuestionId; // retrieve the questionId from the Model
        const newOptionText = document.getElementById('newOptionText').value;
        const url = `/Administrator/Question/InsertNewOption?questionId=${questionId}&optionText=${newOptionText}`;
        window.location.href = url;
    }
</script>

ergo-web2-2023/Areas/Administrator/Views/Question/CreateQuestion.cshtml
@model ergo_web2_2023.Areas.Administrator.ViewModels.QuestionVM
@using ergo_web2_2023.Models.Enums;
<link rel="stylesheet" href="~/css/editAndCreate.css">

@{
    ViewData["Title"] = "CreateQuestion";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
    var questionTypes = Enum.GetValues(typeof(QuestionType)).Cast<QuestionType>().Select(x => new SelectListItem { Text = x.ToString(), Value = ((int)x).ToString() });
}

<div class="container align-content-center">
    <h1>New Question</h1>

    <br />
    <div class="scrollable-container">
        <div class="row container-row">
            <div class="col-4"></div>
            <div class="col-md-4">
                <form asp-action="CreateQuestion">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Type" class="control-label"></label>
                        <select asp-for="Type" class="form-control" asp-items="questionTypes"></select>
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Hint" class="control-label"></label>
                        <input asp-for="Hint" class="form-control" />
                        <span asp-validation-for="Hint" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ergo-web2-2023/Areas/Administrator/Views/Question/Delete.cshtml
@model ergo_web2_2023.Areas.Administrator.ViewModels.QuestionVM
<link rel="stylesheet" href="~/css/editAndCreate.css">

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div class="container align-content-center">
    <h1>Delete this question?</h1>
    <br />
    <div class="scrollable-container">
        <div class="row">
            <div class="col-4"></div>

            <div class="col-md-4">
                @using (Html.BeginForm("Delete", "Question", new { id = Model.QuestionId }, FormMethod.Post))
                {
                    <div>
                        <label class="control-label">Title</label>
                        <input value="@Model.Title" class="form-control" readonly />
                    </div>
                    <div>
                        <label class="control-label">Description</label>
                        <input value="@Model.Description" class="form-control" readonly />
                    </div>
                    <div>
                        <label class="control-label">Type</label>
                        @if (@Model.Type == 1)
                        {
                            <input value="Open vraag" class="form-control" readonly />
                        }
                        else
                        {
                            <input value="Meerkeuzevraag" class="form-control" readonly />
                        }
                    </div>
                    <div>
                        <label class="control-label">Hint</label>
                        <input value="@Model.Hint" class="form-control" readonly />
                    </div>

                    @Html.AntiForgeryToken()
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-6">
                                <button type="submit" class="btn btn-danger delete">Delete</button>
                            </div>
                            <div class="col-6">
                                <button type="button" class="btn cancel" onclick="location.href='@Url.Action("ListAllQuestions")'">Cancel</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</div>

ergo-web2-2023/Areas/Administrator/Views/Question/EditQuestion.cshtml
@model ergo_web2_2023.Areas.Administrator.ViewModels.QuestionEditVM
@using ergo_web2_2023.Models.Enums;
<link rel="stylesheet" href="~/css/editAndCreate.css">

@{
    ViewData["Title"] = "EditQuestion";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
    var questionTypes = Enum.GetValues(typeof(QuestionType)).Cast<QuestionType>().Select(x => new SelectListItem { Text = x.ToString(), Value = ((int)x).ToString() });
}
<div class="container align-content-center">

    <h1>Edit Question</h1>

    <br />
    <div class="scrollable-container">
        <div class="row">
            <div class="col-4"></div>

            <div class="col-md-4">
                <form asp-action="EditQuestion">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="QuestionId" class="control-label"></label>
                        <input asp-for="QuestionId" class="form-control" readonly />
                        <span asp-validation-for="QuestionId" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                    <br />

                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <br />

                    <div class="form-group">
                        <label asp-for="Type" class="control-label"></label>
                        <select asp-for="Type" id="typeDropdown" class="form-control" asp-items="questionTypes"></select>
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Hint" class="control-label"></label>
                        <input asp-for="Hint" class="form-control" />
                        <span asp-validation-for="Hint" class="text-danger"></span>
                    </div>
                    <br />

                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
                <div class="text-center" id="optionBtn">
                    @if (Model.Type == 2)
                    {
                        <div class="btn">
                            <a class="btn" asp-action="AddOptions" asp-route-id="@Model.QuestionId">Add Options</a>
                        </div>
                    }
                </div>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</div>




@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            function loadOptions() {
                var selectedType = $('#typeDropdown').val();
                var optionBtn = $('#optionBtn');

                if (selectedType === '2') {
                    optionBtn.html('<div class="btn"><a class="btn" href="'
                        + '@Url.Action("AddOptions", new { id = Model.QuestionId })'
                        + '">Add Options</a></div>');
                } else {
                    optionBtn.empty();
                }
            }

            $('#typeDropdown').on('change', function () {
                loadOptions();
            });

            loadOptions();
        });
    </script>
}

ergo-web2-2023/Areas/Administrator/Views/Question/ListAllQuestions.cshtml
@model IEnumerable<ergo_web2_2023.Areas.Administrator.ViewModels.QuestionVM>

@{
    ViewData["Title"] = "ListAllQuestions";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div id="quick-actions">
    <h3>Quick Actions</h3>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-3 mb-2" onclick="location.href='@Url.Action("CreateQuestion", "Question", new { area = "Administrator" })';" style="cursor: pointer;">
            <div class="card text-center">
                <div class="card-body fw-bold">
                    <p>
                        <h3 class="plus">+</h3>
                        <span>Create Question</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="content">
    <div class="content-title">
        <h3>All Questions</h3>
    </div>
    <div class="row content-cards">
        @foreach (var item in Model)
        {
            <div class="col-12 col-md-6 col-lg-3 mb-2">
                <div class="card content-card">
                    <div class="card-body">
                        <h5 class="formtitle">@Html.DisplayFor(modelItem => item.Title)</h5>
                        @if (item.Description == null)
                        {
                            <p class="description">Geen Description</p>
                        }
                        else
                        {
                            <p class="description">Desc.: @Html.DisplayFor(modelItem => item.Description)</p>
                        }
                        @if (item.Type == 1)
                        {
                            <p class="description">Type: Open vraag</p>
                        }
                        else
                        {
                            <p class="description">Type: Meerkeuzevraag</p>
                        }
                    </div>
                    <div class="actions">
                        <a asp-action="EditQuestion" asp-route-id="@item.QuestionId"><img height="30px" src="~/images/edit.png" /></a> |
                        <a asp-action="Delete" asp-route-id="@item.QuestionId"><img height="30px" src="~/images/delete.png" /></a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>